<a href="https://colab.research.google.com/github/hanvita1/machinelearning/blob/master/day_3_session_2_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a Pandas program to create and display a one-dimensional array using series containing even numbers upto 10000

In [1]:
import pandas as pd
l=([i for i in range(0,10000) if i%2==0])
ds = pd.Series(l) 
print(ds)

0          0
1          2
2          4
3          6
4          8
        ... 
4995    9990
4996    9992
4997    9994
4998    9996
4999    9998
Length: 5000, dtype: int64


Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type

In [2]:
import pandas as pd
d = pd.Series([i for i in range(1000,2001) if i%5==0]) 
print(d)
print(d.tolist())
print(type(d.tolist()))

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
196    1980
197    1985
198    1990
199    1995
200    2000
Length: 201, dtype: int64
[1000, 1005, 1010, 1015, 1020, 1025, 1030, 1035, 1040, 1045, 1050, 1055, 1060, 1065, 1070, 1075, 1080, 1085, 1090, 1095, 1100, 1105, 1110, 1115, 1120, 1125, 1130, 1135, 1140, 1145, 1150, 1155, 1160, 1165, 1170, 1175, 1180, 1185, 1190, 1195, 1200, 1205, 1210, 1215, 1220, 1225, 1230, 1235, 1240, 1245, 1250, 1255, 1260, 1265, 1270, 1275, 1280, 1285, 1290, 1295, 1300, 1305, 1310, 1315, 1320, 1325, 1330, 1335, 1340, 1345, 1350, 1355, 1360, 1365, 1370, 1375, 1380, 1385, 1390, 1395, 1400, 1405, 1410, 1415, 1420, 1425, 1430, 1435, 1440, 1445, 1450, 1455, 1460, 1465, 1470, 1475, 1480, 1485, 1490, 1495, 1500, 1505, 1510, 1515, 1520, 1525, 1530, 1535, 1540, 1545, 1550, 1555, 1560, 1565, 1570, 1575, 1580, 1585, 1590, 1595, 1600, 1605, 1610, 1615, 1620, 1625, 1630, 1635, 1640, 1645, 1650, 1655, 1660, 1665, 1670, 1675, 1680, 1685, 1690, 1695, 1

Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [3]:
import pandas as pd
l1=([i for i in range(1,101) if i%2==0])
l2=([i for i in range(1,100) if i%2==1])
d1=pd.Series(l1)
d2=pd.Series(l2)
print(f'Addition Of  Two Series:\n{d1+d2}')
print(f'Subtraction Of  Two Series:\n{d1-d2}')
print(f'Multiplication Of  Two Series:\n{d1*d2}')
print(f'Division Of  Two Series:\n{d1/d2}')

Addition Of  Two Series:
0       3
1       7
2      11
3      15
4      19
5      23
6      27
7      31
8      35
9      39
10     43
11     47
12     51
13     55
14     59
15     63
16     67
17     71
18     75
19     79
20     83
21     87
22     91
23     95
24     99
25    103
26    107
27    111
28    115
29    119
30    123
31    127
32    131
33    135
34    139
35    143
36    147
37    151
38    155
39    159
40    163
41    167
42    171
43    175
44    179
45    183
46    187
47    191
48    195
49    199
dtype: int64
Subtraction Of  Two Series:
0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
30    1
31    1
32    1
33    1
34    1
35    1
36    1
37    1
38    1
39    1
40    1
41    1
42    1
43    1
44    1
45    1
46    1
47    1
48    1
49    1
dtype: int64
Multiplication Of  Tw

Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]

In [4]:
import pandas as pd
l1=([i for i in range(1,1000) if i%7==0])
l2=([i for i in range(1,1000) if i%11==0])
d1 = pd.Series(l1)
d2 = pd.Series(l2)
print("Compare the elements of the said Series:")
print("Equals:")
for i in range (len(l2)):
  print(i," ",d1[i]==d2[i])
print("Greater than:")
for i in range(len(l2)):
  print(i," ",d1[i]>d2[i])
print("Less than:")
for i in range(len(l2)):
  print(i," ",d1[i]<d2[i])

Compare the elements of the said Series:
Equals:
0   False
1   False
2   False
3   False
4   False
5   False
6   False
7   False
8   False
9   False
10   False
11   False
12   False
13   False
14   False
15   False
16   False
17   False
18   False
19   False
20   False
21   False
22   False
23   False
24   False
25   False
26   False
27   False
28   False
29   False
30   False
31   False
32   False
33   False
34   False
35   False
36   False
37   False
38   False
39   False
40   False
41   False
42   False
43   False
44   False
45   False
46   False
47   False
48   False
49   False
50   False
51   False
52   False
53   False
54   False
55   False
56   False
57   False
58   False
59   False
60   False
61   False
62   False
63   False
64   False
65   False
66   False
67   False
68   False
69   False
70   False
71   False
72   False
73   False
74   False
75   False
76   False
77   False
78   False
79   False
80   False
81   False
82   False
83   False
84   False
85   False
86   False
87  

Write a Pandas program to convert a NumPy array to a Pandas series.
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]

In [5]:
import numpy as np
import pandas as pd
l1=([i for i in range(1,1001) if i%10==0])
a = np.array(l1)
print(f"NumPy array:\n{a}")
print(f"Converted Pandas series:\n{pd.Series(a)}")

NumPy array:
[  10   20   30   40   50   60   70   80   90  100  110  120  130  140
  150  160  170  180  190  200  210  220  230  240  250  260  270  280
  290  300  310  320  330  340  350  360  370  380  390  400  410  420
  430  440  450  460  470  480  490  500  510  520  530  540  550  560
  570  580  590  600  610  620  630  640  650  660  670  680  690  700
  710  720  730  740  750  760  770  780  790  800  810  820  830  840
  850  860  870  880  890  900  910  920  930  940  950  960  970  980
  990 1000]
Converted Pandas series:
0       10
1       20
2       30
3       40
4       50
      ... 
95     960
96     970
97     980
98     990
99    1000
Length: 100, dtype: int64


Write a Pandas program to convert a given Series to an array.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [6]:
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print(f"Original Data Series:\n{s1}")
print(f"Series to an array:\n{np.array(s1.values.tolist())}")

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array:
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


Write a Pandas program to sort a given Series.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [7]:
import pandas as pd
s = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print(f"Original Data Series:\n{s}")
print(pd.Series(s).sort_values())

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
0          100
1          200
2          300
6       300.12
3          400
7          400
4          500
9        great
8           is
10    language
5       python
dtype: object


Write a Pandas program to create a subsets of a given series based on value and condition.
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]
value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5

In [8]:
import pandas as pd
s = pd.Series(([i for i in range(1,1001) if i%10==0]))
print(f"Original Data Series:\n{s}")
print(f"Subset of the above Data Series:\n{s[s%7==0]}\n{s[s%5==0]}")


Original Data Series:
0       10
1       20
2       30
3       40
4       50
      ... 
95     960
96     970
97     980
98     990
99    1000
Length: 100, dtype: int64
Subset of the above Data Series:
6      70
13    140
20    210
27    280
34    350
41    420
48    490
55    560
62    630
69    700
76    770
83    840
90    910
97    980
dtype: int64
0       10
1       20
2       30
3       40
4       50
      ... 
95     960
96     970
97     980
98     990
99    1000
Length: 100, dtype: int64


Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

In [9]:
import pandas as pd
l=[2]
for v in range(3,1001):
  for n in range(2, v): 
    if (v % n) == 0: 
      break
    elif(n==v-1):
      l.append(v)
s = pd.Series(l)
print(f"Original Data Series:\n{s}")
print(f"Mean of the said Data Series:\n{s.mean()}")
print(f"Standard deviation of the said Data Series:\n{s.std()}")
print(f"Max of the said Data Series:\n{s.max()}")
print(f"Min of the said Data Series:\n{s.min()}")

Original Data Series:
0        2
1        3
2        5
3        7
4       11
      ... 
163    971
164    977
165    983
166    991
167    997
Length: 168, dtype: int64
Mean of the said Data Series:
453.13690476190476
Standard deviation of the said Data Series:
298.19241719366255
Max of the said Data Series:
997
Min of the said Data Series:
2


Write a Pandas program to get the elements of an array values into column-wise.
Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}

In [10]:
import pandas as pd
l1=([i for i in range(0,1001) if i%7!=0 and i%2!=0])
l2=([i for i in range(0,1001) if i%2==0 and i%5!=0])
l3=([i for i in range(0,1001) if i%2!=0 and i%3!=0])
if(len(l1)>len(l2) and len(l1)>len(l3)):
  for i in range(len(l1)-len(l2)):
    l2.append("null")
  for i in range(len(l1)-len(l3)):
    l3.append("null")
elif(len(l2)>len(l1) and len(l3)>len(l3)):
  for i in range(len(l2)-len(l1)):
    l1.append("null")
  for i in range(len(l2)-len(l3)):
    l3.append("null")
else:
  for i in range(len(l3)-len(l2)):
    l2.append("null")
  for i in range(len(l3)-len(l1)):
    l1.append("null")
print(len(l1),len(l2),len(l3))
df = pd.DataFrame({'X':l1, 'Y':l2,'Z':l3});
df

429 429 429


X     Y     Z
0      1     2     1
1      3     4     5
2      5     6     7
3      9     8    11
4     11    12    13
..   ...   ...   ...
424  991  null  null
425  993  null  null
426  995  null  null
427  997  null  null
428  999  null  null

[429 rows x 3 columns]

Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.Write a Pandas program to get the details of theseventh movie of the DataFrame for any particular three fields (movie_metadata.csv file).

In [ ]:
import pandas as pd
df = pd.read_csv('/movies.csv')
small_df = df[['rating','budget','year']]
print(f"First 10 rows of the DataFrame:\n{small_df.head(10)}")

Write a Pandas program to sort the DataFrame based on country and language from dataset of movie_metadata.csv

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('/movies.csv')
print(f"sorted by country:\n{df.sort_values('country')}")
print(f"sorted by lang:\n{df.sort_values('lang')}")


Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields (movie_metadatacsvfile).

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('/movies.csv')
small_df = df[['rating','budget','year']]
print(f"{small_df.iloc[7]}")

Write a Pandas program to get the details of the movies record number divisable by 5 of the DataFrame (movie_metadata.csv file).

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('/movies.csv')
small_df = df[['rating','budget','year']]
for i in range(1,len(df)+1):
  if i%5==0:
    print(f"{small_df.iloc[i]}\n")

Write a Pandas program to find the mean and standard deviation, maximum and minimum of the data of 50 students Python marks stored in a CSV file called Python_mark.csv( you have to create the file yourself like rollno,mark for 50 records)

In [ ]:
import pandas as pd
df = pd.read_csv('/Python_marks.csv')
print("file content: ",df)
print ('Mean : ' + str(df['marks'].mean()))
print ('S.D: ' + str(df['marks'].std() ))
print ('Minimum : ' + str(df['marks'].min()))
print ('Maximum : ' + str(df['marks'].max()))

Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable.

In [15]:
import numpy as np
x = np.random.random((4,4))
print(x)
print("2nd and 3rd rows of the above array:")
y= x[1:3, :]
print(y)

[[0.678503   0.60378072 0.99267992 0.96887773]
 [0.6628342  0.90370868 0.43994346 0.98391592]
 [0.1846509  0.20784762 0.44202466 0.5262069 ]
 [0.25631132 0.90246882 0.82276064 0.51920752]]
2nd and 3rd rows of the above array:
[[0.6628342  0.90370868 0.43994346 0.98391592]
 [0.1846509  0.20784762 0.44202466 0.5262069 ]]


Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.


In [14]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.75954197 0.84841493 0.83458102 0.64035    0.57017178 0.02074438
  0.90157257 0.68186243 0.32846385 0.54009195]
 [0.27237306 0.11559877 0.3694206  0.64521826 0.126841   0.05881914
  0.71574693 0.50278099 0.90943833 0.78723766]
 [0.28521134 0.19541835 0.59319074 0.23400668 0.53408054 0.62370414
  0.90984727 0.85957307 0.47368076 0.20679669]
 [0.77475404 0.67327657 0.00475845 0.69743195 0.03603876 0.1258494
  0.21784186 0.65189765 0.16996585 0.84706609]
 [0.72590825 0.2135985  0.38032611 0.70872459 0.56876246 0.79661563
  0.79654611 0.61569642 0.97401014 0.36018249]
 [0.09874227 0.9331216  0.61261884 0.92007463 0.75264288 0.12900366
  0.05323752 0.12824947 0.72778832 0.21051693]
 [0.26804997 0.9862103  0.12243367 0.6260775  0.32317702 0.41594798
  0.9549059  0.48111102 0.08364443 0.27375179]
 [0.27433833 0.94114207 0.60775677 0.08140175 0.98117465 0.19005905
  0.24043709 0.51099499 0.45294916 0.33355465]
 [0.84087433 0.96198559 0.76908355 0.64913964 0.74854934 0.509413